import type { Metadata } from "next";
import { Nunito_Sans, Raleway, Rubik } from "next/font/google";
import "./globals.css";
import Navbar from "./components/Navbar";
import Footer from "./components/Footer";
import Sidebar from "./components/Sidebar";
import { SidebarProvider } from "./context/SidebarContext";
import { ThemeProvider } from './context/ThemeContext';

const nunitoSans = Nunito_Sans({
  subsets: ['latin'],
  variable: '--font-nunito-sans',
});

const raleway = Raleway({
  subsets: ['latin'],
  variable: '--font-raleway',
});

const rubik = Rubik({
  subsets: ['latin'],
  variable: '--font-rubik',
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body className={`
        ${nunitoSans.variable} ${raleway.variable} ${rubik.variable} 
        font-sans antialiased 
        bg-white dark:bg-gray-900 
        text-gray-800 dark:text-white
      `}>
        <ThemeProvider>
          <SidebarProvider>
            <Navbar />
            <div className="flex">
              <Sidebar />
              <main className="flex-1 sm:ml-64 pt-16 min-h-screen">
                {children}
              </main>
            </div>
            <Footer />
          </SidebarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
